CREATE TYPE "tipo_dato" AS ENUM (
  'int',
  'float',
  'bool',
  'list'
);

CREATE TABLE "familias" (
  "id_familia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL
);

CREATE TABLE "atributos" (
  "id_atributo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_familia" INT,
  "nombre_atributo" varchar NOT NULL,
  "tipo_dato" tipo_dato NOT NULL,
  "unidad" varchar NOT NULL,
  "es_obligatorio" BOOLEAN DEFAULT false,
  "orden" SMALLINT NOT NULL,
  "opciones_atributos" varchar[]
);

CREATE TABLE "opciones_atributos" (
  "id_opcion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_atributo" INT,
  "valor" varchar NOT NULL,
  "orden" SMALLINT
);

CREATE TABLE "productos" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar UNIQUE NOT NULL,
  "denominacion" varchar NOT NULL,
  "id_familia" INT NOT NULL
);

CREATE TABLE "revisiones_productos" (
  "id_producto_revision" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" INT NOT NULL,
  "version" INT NOT NULL,
  "fecha_revision" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "autor_revision" varchar NOT NULL,
  "comentarios_revision" varchar NOT NULL,
  "vigente" BOOLEAN
);

CREATE TABLE "jerarquias_productos" (
  "id_padre" INT NOT NULL,
  "id_hijo" INT NOT NULL,
  "cantidad" INT NOT NULL DEFAULT 1
);

CREATE TABLE "productos_atributos_valores" (
  "id_valor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto_revision" INT NOT NULL,
  "id_atributo" INT NOT NULL,
  "valor_int" INT,
  "valor_float" FLOAT,
  "valor_bool" BOOLEAN,
  "id_valor_enum" INT
);

CREATE TABLE "procesos" (
  "id_proceso" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(21) UNIQUE NOT NULL
);

CREATE TABLE "revisiones_procesos" (
  "id_proceso_revision" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_proceso" INT NOT NULL,
  "fecha_revision" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "num_revision" INT NOT NULL,
  "autor_revision" VARCHAR,
  "comentarios_revision" VARCHAR,
  "vigente" BOOLEAN,
  "id_secuencia" INT
);

CREATE TABLE "secuencias" (
  "id_secuencia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_centro_de_costo" INT NOT NULL,
  "tiempo_setup" "DECIMAL(6,2)",
  "tiempo_prod" "DECIMAL(6,2)"
);

CREATE TABLE "secuencias_operaciones" (
  "id_secuencia" INT,
  "id_operacion" INT,
  "orden" SMALLINT,
  PRIMARY KEY ("id_secuencia", "id_operacion")
);

CREATE TABLE "secuencias_recursos" (
  "id_secuencia" INT,
  "id_recurso" INT,
  "es_principal" BOOLEAN,
  PRIMARY KEY ("id_secuencia", "id_recurso")
);

CREATE TABLE "procesos_atributos_requisitos" (
  "id_requisito" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_proceso_revision" INT NOT NULL,
  "id_atributo" INT NOT NULL,
  "operador" operador_proceso,
  "valor_int" INT,
  "valor_float" FLOAT,
  "valor_bool" BOOLEAN,
  "id_valor_enum" INT
);

CREATE TABLE "operaciones" (
  "id_operacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL,
  "descripcion" TEXT
);

CREATE TABLE "recursos" (
  "id_recurso" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar NOT NULL,
  "nombre" varchar NOT NULL,
  "descripcion" TEXT,
  "capacidades" JSONB,
  "id_centro_de_costo" INT NOT NULL
);

CREATE TABLE "centros_de_costo" (
  "id_centro_de_costo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" VARCHAR,
  "descripcion" TEXT
);

ALTER TABLE "atributos" ADD FOREIGN KEY ("id_familia") REFERENCES "familias" ("id_familia");

ALTER TABLE "opciones_atributos" ADD FOREIGN KEY ("id_atributo") REFERENCES "atributos" ("id_atributo");

ALTER TABLE "productos" ADD FOREIGN KEY ("id_familia") REFERENCES "familias" ("id_familia");

ALTER TABLE "revisiones_productos" ADD FOREIGN KEY ("id_producto") REFERENCES "productos" ("id_producto");

ALTER TABLE "jerarquias_productos" ADD FOREIGN KEY ("id_padre") REFERENCES "productos" ("id_producto");

ALTER TABLE "jerarquias_productos" ADD FOREIGN KEY ("id_hijo") REFERENCES "productos" ("id_producto");

ALTER TABLE "productos_atributos_valores" ADD FOREIGN KEY ("id_producto_revision") REFERENCES "revisiones_productos" ("id_producto_revision");

ALTER TABLE "productos_atributos_valores" ADD FOREIGN KEY ("id_atributo") REFERENCES "atributos" ("id_atributo");

ALTER TABLE "productos_atributos_valores" ADD FOREIGN KEY ("id_valor_enum") REFERENCES "opciones_atributos" ("id_opcion");

ALTER TABLE "revisiones_procesos" ADD FOREIGN KEY ("id_proceso") REFERENCES "procesos" ("id_proceso");

ALTER TABLE "revisiones_procesos" ADD FOREIGN KEY ("id_secuencia") REFERENCES "secuencias" ("id_secuencia");

ALTER TABLE "secuencias" ADD FOREIGN KEY ("id_centro_de_costo") REFERENCES "centros_de_costo" ("id_centro_de_costo");

ALTER TABLE "secuencias_operaciones" ADD FOREIGN KEY ("id_secuencia") REFERENCES "secuencias" ("id_secuencia");

ALTER TABLE "secuencias_operaciones" ADD FOREIGN KEY ("id_operacion") REFERENCES "operaciones" ("id_operacion");

ALTER TABLE "secuencias_recursos" ADD FOREIGN KEY ("id_secuencia") REFERENCES "secuencias" ("id_secuencia");

ALTER TABLE "secuencias_recursos" ADD FOREIGN KEY ("id_recurso") REFERENCES "recursos" ("id_recurso");

ALTER TABLE "procesos_atributos_requisitos" ADD FOREIGN KEY ("id_proceso_revision") REFERENCES "revisiones_procesos" ("id_proceso_revision");

ALTER TABLE "procesos_atributos_requisitos" ADD FOREIGN KEY ("id_atributo") REFERENCES "atributos" ("id_atributo");

ALTER TABLE "procesos_atributos_requisitos" ADD FOREIGN KEY ("id_valor_enum") REFERENCES "opciones_atributos" ("id_opcion");

ALTER TABLE "recursos" ADD FOREIGN KEY ("id_centro_de_costo") REFERENCES "centros_de_costo" ("id_centro_de_costo");
